/**
 * Mail Baby API
 * This is an API defintion for accesssing the Mail.Baby mail service.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: detain@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.model


/**
 * = Email details =
 *
 * Details for an Email
 *
 * @param subject The subject or title of the email for example: '''Your Package has been Delivered!'''
 * @param body The main email contents. for example: '''The package you ordered on 2021-01-23 has been delivered. If the package is broken into many pieces, please blaim someone else.
'''
 * @param from 
 * @param to The Contact whom is the primary recipient of this email.
 * @param id The ID of the Mail order within our system to use as the Mail Account. for example: '''5000'''
 * @param replyto Optional list of Contacts that specify where replies to the email should be sent instead of the _from_ address.
 * @param cc Optional list of Contacts that should receive copies of the email.  They are listed on the email and anyone getting the email can see this full list of Contacts who received the email as well.
 * @param bcc Optional list of Contacts that should receive copies of the email.  They are hidden on the email and anyone gettitng the email would not see the other people getting the email in this list.
 * @param attachments Optional file attachments to include in the email
 */
case class SendMail (
  subject: String,
  body: String,
  from: MailContact,
  to: List[MailContact],
  id: Long,
  replyto: Option[List[MailContact]] = None,
  cc: Option[List[MailContact]] = None,
  bcc: Option[List[MailContact]] = None,
  attachments: Option[List[MailAttachment]] = None
)

