/* tslint:disable */
/* eslint-disable */
/**
 * MailBaby Email Delivery API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**   # 📌 Overview  This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).   # 🔐 Authentication  In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.    We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * An Email Contact
 * @export
 * @interface SendMailAdvCcInner
 */
export interface SendMailAdvCcInner {
    /**
     * The email address
     * @type {string}
     * @memberof SendMailAdvCcInner
     */
    email: string;
    /**
     * (optional) Name to use for the CC contact.
     * @type {string}
     * @memberof SendMailAdvCcInner
     */
    name?: string;
}

/**
 * Check if a given object implements the SendMailAdvCcInner interface.
 */
export function instanceOfSendMailAdvCcInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function SendMailAdvCcInnerFromJSON(json: any): SendMailAdvCcInner {
    return SendMailAdvCcInnerFromJSONTyped(json, false);
}

export function SendMailAdvCcInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendMailAdvCcInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SendMailAdvCcInnerToJSON(value?: SendMailAdvCcInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'name': value.name,
    };
}

