"""
    Mail Baby API

    This is an API for accesssing the mail services.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: detain@interserver.net
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.mail_attachment import MailAttachment
from openapi_client.model.mail_contact import MailContact
globals()['MailAttachment'] = MailAttachment
globals()['MailContact'] = MailContact
from openapi_client.model.send_mail import SendMail


class TestSendMail(unittest.TestCase):
    """SendMail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSendMail(self):
        """Test SendMail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SendMail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
