# coding: utf-8

"""
    MailBaby Email Delivery and Management Service API

    **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 

    The version of the OpenAPI document: 1.1.0
    Contact: support@interserver.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.mail_block_click_house import MailBlockClickHouse  # noqa: E501
from openapi_client.rest import ApiException

class TestMailBlockClickHouse(unittest.TestCase):
    """MailBlockClickHouse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test MailBlockClickHouse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MailBlockClickHouse`
        """
        model = openapi_client.models.mail_block_click_house.MailBlockClickHouse()  # noqa: E501
        if include_optional :
            return MailBlockClickHouse(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                var_from = '', 
                message_id = '', 
                subject = '', 
                to = ''
            )
        else :
            return MailBlockClickHouse(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                var_from = '',
                message_id = '',
                subject = '',
                to = '',
        )
        """

    def testMailBlockClickHouse(self):
        """Test MailBlockClickHouse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
