/*
 * MailBaby Email Delivery and Management Service API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * OpenAPI spec version: 1.3.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.78
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MailBabyEmailDeliveryAndManagementServiceApi);
  }
}(this, function(expect, MailBabyEmailDeliveryAndManagementServiceApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('MailStatsTypeVolumeTo', function() {
      beforeEach(function() {
        instance = new MailBabyEmailDeliveryAndManagementServiceApi.MailStatsTypeVolumeTo();
      });

      it('should create an instance of MailStatsTypeVolumeTo', function() {
        // TODO: update the code to test MailStatsTypeVolumeTo
        expect(instance).to.be.a(MailBabyEmailDeliveryAndManagementServiceApi.MailStatsTypeVolumeTo);
      });

      it('should have the property clientdomain_com (base name: "client@domain.com")', function() {
        // TODO: update the code to test the property clientdomain_com
        expect(instance).to.have.property('clientdomain_com');
        // expect(instance.clientdomain_com).to.be(expectedValueLiteral);
      });

      it('should have the property usersite_net (base name: "user@site.net")', function() {
        // TODO: update the code to test the property usersite_net
        expect(instance).to.have.property('usersite_net');
        // expect(instance.usersite_net).to.be(expectedValueLiteral);
      });

      it('should have the property salescompany_com (base name: "sales@company.com")', function() {
        // TODO: update the code to test the property salescompany_com
        expect(instance).to.have.property('salescompany_com');
        // expect(instance.salescompany_com).to.be(expectedValueLiteral);
      });

      it('should have the property clientanothersite_com (base name: "client@anothersite.com")', function() {
        // TODO: update the code to test the property clientanothersite_com
        expect(instance).to.have.property('clientanothersite_com');
        // expect(instance.clientanothersite_com).to.be(expectedValueLiteral);
      });

    });
  });

}));
