/*
 * Mail Baby API
 *
 * This is an API defintion for accesssing the Mail.Baby mail service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: detain@interserver.net
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing DefaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DefaultApiTests
    {
        private DefaultApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new DefaultApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DefaultApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOf' DefaultApi
            //Assert.IsInstanceOf(typeof(DefaultApi), instance);
        }

        
        /// <summary>
        /// Test GetMailOrders
        /// </summary>
        [Test]
        public void GetMailOrdersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //var response = instance.GetMailOrders(id);
            //Assert.IsInstanceOf(typeof(List<MailOrder>), response, "response is List<MailOrder>");
        }
        
        /// <summary>
        /// Test PingServer
        /// </summary>
        [Test]
        public void PingServerTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.PingServer();
            
        }
        
        /// <summary>
        /// Test PlaceMailOrder
        /// </summary>
        [Test]
        public void PlaceMailOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //MailOrder mailOrder = null;
            //instance.PlaceMailOrder(mailOrder);
            
        }
        
        /// <summary>
        /// Test SendAdvMail
        /// </summary>
        [Test]
        public void SendAdvMailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendMailAdv sendMailAdv = null;
            //var response = instance.SendAdvMail(sendMailAdv);
            //Assert.IsInstanceOf(typeof(GenericResponse), response, "response is GenericResponse");
        }
        
        /// <summary>
        /// Test SendMail
        /// </summary>
        [Test]
        public void SendMailTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SendMail sendMail = null;
            //var response = instance.SendMail(sendMail);
            //Assert.IsInstanceOf(typeof(GenericResponse), response, "response is GenericResponse");
        }
        
        /// <summary>
        /// Test ValidateMailOrder
        /// </summary>
        [Test]
        public void ValidateMailOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ValidateMailOrder();
            
        }
        
        /// <summary>
        /// Test ViewMailLogById
        /// </summary>
        [Test]
        public void ViewMailLogByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //long? id = null;
            //string searchString = null;
            //int? skip = null;
            //int? limit = null;
            //var response = instance.ViewMailLogById(id, searchString, skip, limit);
            //Assert.IsInstanceOf(typeof(List<MailLog>), response, "response is List<MailLog>");
        }
        
    }

}
