# coding: utf-8

# flake8: noqa
"""
    MailBaby Email Delivery and Management Service API

    **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 

    The version of the OpenAPI document: 1.3.0
    Contact: support@interserver.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from openapi_client.models.deny_rule_new import DenyRuleNew
from openapi_client.models.deny_rule_record import DenyRuleRecord
from openapi_client.models.email_address_name import EmailAddressName
from openapi_client.models.email_address_types import EmailAddressTypes
from openapi_client.models.email_addresses_types import EmailAddressesTypes
from openapi_client.models.error_message import ErrorMessage
from openapi_client.models.generic_response import GenericResponse
from openapi_client.models.mail_attachment import MailAttachment
from openapi_client.models.mail_block_click_house import MailBlockClickHouse
from openapi_client.models.mail_block_rspamd import MailBlockRspamd
from openapi_client.models.mail_blocks import MailBlocks
from openapi_client.models.mail_log import MailLog
from openapi_client.models.mail_log_entry import MailLogEntry
from openapi_client.models.mail_order import MailOrder
from openapi_client.models.mail_stats_type import MailStatsType
from openapi_client.models.mail_stats_type_volume import MailStatsTypeVolume
from openapi_client.models.mail_stats_type_volume_from import MailStatsTypeVolumeFrom
from openapi_client.models.mail_stats_type_volume_ip import MailStatsTypeVolumeIp
from openapi_client.models.mail_stats_type_volume_to import MailStatsTypeVolumeTo
from openapi_client.models.raw_mail import RawMail
from openapi_client.models.send_mail import SendMail
from openapi_client.models.send_mail_adv import SendMailAdv

