# MailBaby Email Delivery API
#
# **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**   # 📌 Overview  This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).   # 🔐 Authentication  In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.    We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
#
# The version of the OpenAPI document: 1.0.0
# Contact: support@interserver.net
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title SendMailAdv
#'
#' @description SendMailAdv Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field subject  character 
#'
#' @field body  character 
#'
#' @field from  \link{SendMailAdvFrom} 
#'
#' @field to  list( \link{SendMailAdvToInner} ) 
#'
#' @field replyto  list( \link{SendMailAdvReplytoInner} ) [optional]
#'
#' @field cc  list( \link{SendMailAdvCcInner} ) [optional]
#'
#' @field bcc  list( \link{SendMailAdvBccInner} ) [optional]
#'
#' @field attachments  list( \link{SendMailAdvAttachmentsInner} ) [optional]
#'
#' @field id  integer [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
SendMailAdv <- R6::R6Class(
  'SendMailAdv',
  public = list(
    `subject` = NULL,
    `body` = NULL,
    `from` = NULL,
    `to` = NULL,
    `replyto` = NULL,
    `cc` = NULL,
    `bcc` = NULL,
    `attachments` = NULL,
    `id` = NULL,
    initialize = function(
        `subject`, `body`, `from`, `to`, `replyto`=NULL, `cc`=NULL, `bcc`=NULL, `attachments`=NULL, `id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!missing(`subject`)) {
        stopifnot(is.character(`subject`), length(`subject`) == 1)
        self$`subject` <- `subject`
      }
      if (!missing(`body`)) {
        stopifnot(is.character(`body`), length(`body`) == 1)
        self$`body` <- `body`
      }
      if (!missing(`from`)) {
        stopifnot(R6::is.R6(`from`))
        self$`from` <- `from`
      }
      if (!missing(`to`)) {
        stopifnot(is.vector(`to`), length(`to`) != 0)
        sapply(`to`, function(x) stopifnot(R6::is.R6(x)))
        self$`to` <- `to`
      }
      if (!is.null(`replyto`)) {
        stopifnot(is.vector(`replyto`), length(`replyto`) != 0)
        sapply(`replyto`, function(x) stopifnot(R6::is.R6(x)))
        self$`replyto` <- `replyto`
      }
      if (!is.null(`cc`)) {
        stopifnot(is.vector(`cc`), length(`cc`) != 0)
        sapply(`cc`, function(x) stopifnot(R6::is.R6(x)))
        self$`cc` <- `cc`
      }
      if (!is.null(`bcc`)) {
        stopifnot(is.vector(`bcc`), length(`bcc`) != 0)
        sapply(`bcc`, function(x) stopifnot(R6::is.R6(x)))
        self$`bcc` <- `bcc`
      }
      if (!is.null(`attachments`)) {
        stopifnot(is.vector(`attachments`), length(`attachments`) != 0)
        sapply(`attachments`, function(x) stopifnot(R6::is.R6(x)))
        self$`attachments` <- `attachments`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      SendMailAdvObject <- list()
      if (!is.null(self$`subject`)) {
        SendMailAdvObject[['subject']] <-
          self$`subject`
      }
      if (!is.null(self$`body`)) {
        SendMailAdvObject[['body']] <-
          self$`body`
      }
      if (!is.null(self$`from`)) {
        SendMailAdvObject[['from']] <-
          self$`from`$toJSON()
      }
      if (!is.null(self$`to`)) {
        SendMailAdvObject[['to']] <-
          lapply(self$`to`, function(x) x$toJSON())
      }
      if (!is.null(self$`replyto`)) {
        SendMailAdvObject[['replyto']] <-
          lapply(self$`replyto`, function(x) x$toJSON())
      }
      if (!is.null(self$`cc`)) {
        SendMailAdvObject[['cc']] <-
          lapply(self$`cc`, function(x) x$toJSON())
      }
      if (!is.null(self$`bcc`)) {
        SendMailAdvObject[['bcc']] <-
          lapply(self$`bcc`, function(x) x$toJSON())
      }
      if (!is.null(self$`attachments`)) {
        SendMailAdvObject[['attachments']] <-
          lapply(self$`attachments`, function(x) x$toJSON())
      }
      if (!is.null(self$`id`)) {
        SendMailAdvObject[['id']] <-
          self$`id`
      }

      SendMailAdvObject
    },
    fromJSON = function(SendMailAdvJson) {
      SendMailAdvObject <- jsonlite::fromJSON(SendMailAdvJson)
      if (!is.null(SendMailAdvObject$`subject`)) {
        self$`subject` <- SendMailAdvObject$`subject`
      }
      if (!is.null(SendMailAdvObject$`body`)) {
        self$`body` <- SendMailAdvObject$`body`
      }
      if (!is.null(SendMailAdvObject$`from`)) {
        fromObject <- SendMailAdvFrom$new()
        fromObject$fromJSON(jsonlite::toJSON(SendMailAdvObject$from, auto_unbox = TRUE, digits = NA))
        self$`from` <- fromObject
      }
      if (!is.null(SendMailAdvObject$`to`)) {
        self$`to` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`to`, "array[SendMailAdvToInner]", loadNamespace("openapi"))
      }
      if (!is.null(SendMailAdvObject$`replyto`)) {
        self$`replyto` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`replyto`, "array[SendMailAdvReplytoInner]", loadNamespace("openapi"))
      }
      if (!is.null(SendMailAdvObject$`cc`)) {
        self$`cc` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`cc`, "array[SendMailAdvCcInner]", loadNamespace("openapi"))
      }
      if (!is.null(SendMailAdvObject$`bcc`)) {
        self$`bcc` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`bcc`, "array[SendMailAdvBccInner]", loadNamespace("openapi"))
      }
      if (!is.null(SendMailAdvObject$`attachments`)) {
        self$`attachments` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`attachments`, "array[SendMailAdvAttachmentsInner]", loadNamespace("openapi"))
      }
      if (!is.null(SendMailAdvObject$`id`)) {
        self$`id` <- SendMailAdvObject$`id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`subject`)) {
        sprintf(
        '"subject":
          "%s"
                ',
        self$`subject`
        )},
        if (!is.null(self$`body`)) {
        sprintf(
        '"body":
          "%s"
                ',
        self$`body`
        )},
        if (!is.null(self$`from`)) {
        sprintf(
        '"from":
        %s
        ',
        jsonlite::toJSON(self$`from`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`to`)) {
        sprintf(
        '"to":
        [%s]
',
        paste(sapply(self$`to`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`replyto`)) {
        sprintf(
        '"replyto":
        [%s]
',
        paste(sapply(self$`replyto`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`cc`)) {
        sprintf(
        '"cc":
        [%s]
',
        paste(sapply(self$`cc`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`bcc`)) {
        sprintf(
        '"bcc":
        [%s]
',
        paste(sapply(self$`bcc`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`attachments`)) {
        sprintf(
        '"attachments":
        [%s]
',
        paste(sapply(self$`attachments`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SendMailAdvJson) {
      SendMailAdvObject <- jsonlite::fromJSON(SendMailAdvJson)
      self$`subject` <- SendMailAdvObject$`subject`
      self$`body` <- SendMailAdvObject$`body`
      self$`from` <- SendMailAdvFrom$new()$fromJSON(jsonlite::toJSON(SendMailAdvObject$from, auto_unbox = TRUE, digits = NA))
      self$`to` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`to`, "array[SendMailAdvToInner]", loadNamespace("openapi"))
      self$`replyto` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`replyto`, "array[SendMailAdvReplytoInner]", loadNamespace("openapi"))
      self$`cc` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`cc`, "array[SendMailAdvCcInner]", loadNamespace("openapi"))
      self$`bcc` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`bcc`, "array[SendMailAdvBccInner]", loadNamespace("openapi"))
      self$`attachments` <- ApiClient$new()$deserializeObj(SendMailAdvObject$`attachments`, "array[SendMailAdvAttachmentsInner]", loadNamespace("openapi"))
      self$`id` <- SendMailAdvObject$`id`
      self
    }
  )
)
