/*
 * MailBaby Email Delivery and Management Service API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.*;

import javax.validation.constraints.*;
import javax.validation.Valid;
import io.micronaut.core.annotation.*;
import javax.annotation.Generated;

/**
 * MailStatsTypeVolumeTo
 */
@JsonPropertyOrder({
  MailStatsTypeVolumeTo.JSON_PROPERTY_CLIENT_AT_DOMAIN_COM,
  MailStatsTypeVolumeTo.JSON_PROPERTY_USER_AT_SITE_NET,
  MailStatsTypeVolumeTo.JSON_PROPERTY_SALES_AT_COMPANY_COM,
  MailStatsTypeVolumeTo.JSON_PROPERTY_CLIENT_AT_ANOTHERSITE_COM
})
@JsonTypeName("MailStatsType_volume_to")
@Generated(value="org.openapitools.codegen.languages.JavaMicronautClientCodegen", date="2025-08-22T07:42:24.708059371-04:00[America/New_York]", comments = "Generator version: 7.15.0")
@Introspected
public class MailStatsTypeVolumeTo {
    public static final String JSON_PROPERTY_CLIENT_AT_DOMAIN_COM = "client@domain.com";
    private Integer clientAtDomainCom;

    public static final String JSON_PROPERTY_USER_AT_SITE_NET = "user@site.net";
    private Integer userAtSiteNet;

    public static final String JSON_PROPERTY_SALES_AT_COMPANY_COM = "sales@company.com";
    private Integer salesAtCompanyCom;

    public static final String JSON_PROPERTY_CLIENT_AT_ANOTHERSITE_COM = "client@anothersite.com";
    private Integer clientAtAnothersiteCom;

    public MailStatsTypeVolumeTo() {
    }

    public MailStatsTypeVolumeTo clientAtDomainCom(Integer clientAtDomainCom) {
        this.clientAtDomainCom = clientAtDomainCom;
        return this;
    }

    /**
     * Get clientAtDomainCom
     * @return clientAtDomainCom
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_CLIENT_AT_DOMAIN_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getClientAtDomainCom() {
        return clientAtDomainCom;
    }

    @JsonProperty(JSON_PROPERTY_CLIENT_AT_DOMAIN_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setClientAtDomainCom(Integer clientAtDomainCom) {
        this.clientAtDomainCom = clientAtDomainCom;
    }

    public MailStatsTypeVolumeTo userAtSiteNet(Integer userAtSiteNet) {
        this.userAtSiteNet = userAtSiteNet;
        return this;
    }

    /**
     * Get userAtSiteNet
     * @return userAtSiteNet
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_USER_AT_SITE_NET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getUserAtSiteNet() {
        return userAtSiteNet;
    }

    @JsonProperty(JSON_PROPERTY_USER_AT_SITE_NET)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setUserAtSiteNet(Integer userAtSiteNet) {
        this.userAtSiteNet = userAtSiteNet;
    }

    public MailStatsTypeVolumeTo salesAtCompanyCom(Integer salesAtCompanyCom) {
        this.salesAtCompanyCom = salesAtCompanyCom;
        return this;
    }

    /**
     * Get salesAtCompanyCom
     * @return salesAtCompanyCom
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_SALES_AT_COMPANY_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getSalesAtCompanyCom() {
        return salesAtCompanyCom;
    }

    @JsonProperty(JSON_PROPERTY_SALES_AT_COMPANY_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSalesAtCompanyCom(Integer salesAtCompanyCom) {
        this.salesAtCompanyCom = salesAtCompanyCom;
    }

    public MailStatsTypeVolumeTo clientAtAnothersiteCom(Integer clientAtAnothersiteCom) {
        this.clientAtAnothersiteCom = clientAtAnothersiteCom;
        return this;
    }

    /**
     * Get clientAtAnothersiteCom
     * @return clientAtAnothersiteCom
     */
    @Nullable
    @JsonProperty(JSON_PROPERTY_CLIENT_AT_ANOTHERSITE_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public Integer getClientAtAnothersiteCom() {
        return clientAtAnothersiteCom;
    }

    @JsonProperty(JSON_PROPERTY_CLIENT_AT_ANOTHERSITE_COM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setClientAtAnothersiteCom(Integer clientAtAnothersiteCom) {
        this.clientAtAnothersiteCom = clientAtAnothersiteCom;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        MailStatsTypeVolumeTo mailStatsTypeVolumeTo = (MailStatsTypeVolumeTo) o;
        return Objects.equals(this.clientAtDomainCom, mailStatsTypeVolumeTo.clientAtDomainCom) &&
            Objects.equals(this.userAtSiteNet, mailStatsTypeVolumeTo.userAtSiteNet) &&
            Objects.equals(this.salesAtCompanyCom, mailStatsTypeVolumeTo.salesAtCompanyCom) &&
            Objects.equals(this.clientAtAnothersiteCom, mailStatsTypeVolumeTo.clientAtAnothersiteCom);
    }

    @Override
    public int hashCode() {
        return Objects.hash(clientAtDomainCom, userAtSiteNet, salesAtCompanyCom, clientAtAnothersiteCom);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class MailStatsTypeVolumeTo {\n");
        sb.append("    clientAtDomainCom: ").append(toIndentedString(clientAtDomainCom)).append("\n");
        sb.append("    userAtSiteNet: ").append(toIndentedString(userAtSiteNet)).append("\n");
        sb.append("    salesAtCompanyCom: ").append(toIndentedString(salesAtCompanyCom)).append("\n");
        sb.append("    clientAtAnothersiteCom: ").append(toIndentedString(clientAtAnothersiteCom)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

