/*
 * MailBaby Email Delivery and Management Service API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.DenyRuleNew;
import io.swagger.client.model.DenyRuleRecord;
import io.swagger.client.model.ErrorMessage;
import io.swagger.client.model.GenericResponse;
import io.swagger.client.model.MailBlocks;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for BlockingApi
 */
@Ignore
public class BlockingApiTest {

    private final BlockingApi api = new BlockingApi();

    /**
     * Creates a new email deny rule.
     *
     * Adds a new email deny rule into the system to block new emails that match the given criteria
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addRuleTest() throws Exception {
        String user = null;
        String type = null;
        String data = null;
        GenericResponse response = api.addRule(user, type, data);

        // TODO: test validations
    }
    /**
     * Removes an deny mail rule.
     *
     * Removes one of the configured deny mail rules from the system.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteRuleTest() throws Exception {
        Integer ruleId = null;
        GenericResponse response = api.deleteRule(ruleId);

        // TODO: test validations
    }
    /**
     * Removes an email address from the blocked list
     *
     * Removes an email address from the various block lists. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void delistBlockTest() throws Exception {
        String body = null;
        GenericResponse response = api.delistBlock(body);

        // TODO: test validations
    }
    /**
     * displays a list of blocked email addresses
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getMailBlocksTest() throws Exception {
        MailBlocks response = api.getMailBlocks();

        // TODO: test validations
    }
    /**
     * Displays a listing of deny email rules.
     *
     * Returns a listing of all the deny block rules you have configured.
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRulesTest() throws Exception {
        List<DenyRuleRecord> response = api.getRules();

        // TODO: test validations
    }
}
