// tslint:disable
/**
 * MailBaby Email Delivery API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**   # 📌 Overview  This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).   # 🔐 Authentication  In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.  We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The information to use for the From address in the email. from.
 * @export
 * @interface SendMailAdvFrom
 */
export interface SendMailAdvFrom  {
    /**
     * The email address
     * @type {string}
     * @memberof SendMailAdvFrom
     */
    email: string;
    /**
     * (optional) Name to use for the sending contact.
     * @type {string}
     * @memberof SendMailAdvFrom
     */
    name?: string;
}

export function SendMailAdvFromFromJSON(json: any): SendMailAdvFrom {
    return {
        'email': json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SendMailAdvFromToJSON(value?: SendMailAdvFrom): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'email': value.email,
        'name': value.name,
    };
}


