#
# Mail Baby API
# 
# This is an API for accesssing the mail services.
# The version of the OpenAPI document: 1.0.0
# Contact: detain@interserver.net
# Generated by: https://openapi-generator.tech
#

import json
import tables


type MailAttachment* = object
  ## A File attachment for an email
  filename*: string ## Optional filename to specify for the attachment.
  data*: string ## Contents of the attached file
