/*
 * Mail Baby API
 *
 * This is an API defintion for accesssing the Mail.Baby mail service.
 *
 * API version: 1.0.0
 * Contact: detain@interserver.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse401 struct {
	Code string `json:"code"`
	Message string `json:"message"`
}
