@startuml

title MailBaby Email Delivery API Schemas Diagram

entity GenericResponse {
    status: String
    text: String
}

entity GetMailOrders200ResponseInner {
    * id: Integer
    * status: String
    * username: String
    password: String
    comment: String
}

entity GetMailOrders401Response {
    * code: String
    * message: String
}

entity MailLog {
    * total: Integer
    * skip: Integer
    * limit: Integer
    * emails: List<MailLogEntry>
}

entity MailLogEntry {
    * _id: Integer
    * id: String
    * from: String
    * to: String
    * subject: String
    * messageId: String
    * created: String
    * time: Integer
    * user: String
    * transtype: String
    * transhost: String
    * originhost: String
    * origin: String
    * interface: String
    * date: String
    * sendingZone: String
    * bodySize: Integer
    * sourceMd5: String
    * seq: Integer
    * domain: String
    * recipient: String
    * locked: Integer
    * lockTime: Integer
    * assigned: String
    * queued: String
    * _lock: String
    * logger: String
    * mxPort: Integer
    * connectionKey: String
    * mxHostname: String
    * sentBodyHash: String
    * sentBodySize: Integer
    * md5Match: Integer
}

entity SendMail {
    * to: String
    * from: String
    * subject: String
    * body: String
}

entity SendMailAdv {
    * subject: String
    * body: String
    * from: SendMailAdvFrom
    * to: List<SendMailAdvToInner>
    replyto: List<SendMailAdvReplytoInner>
    cc: List<SendMailAdvCcInner>
    bcc: List<SendMailAdvBccInner>
    attachments: List<SendMailAdvAttachmentsInner>
    id: Long
}

entity SendMailAdvAttachmentsInner {
    * data: File
    filename: String
}

entity SendMailAdvBccInner {
    * email: String
    name: String
}

entity SendMailAdvCcInner {
    * email: String
    name: String
}

entity SendMailAdvFrom {
    * email: String
    name: String
}

entity SendMailAdvReplytoInner {
    * email: String
    name: String
}

entity SendMailAdvToInner {
    * email: String
    name: String
}


SendMailAdv -- SendMailAdvFrom : from
SendMailAdv -- "0..*" SendMailAdvToInner : to
SendMailAdv -- "0..*" SendMailAdvReplytoInner : replyto
SendMailAdv -- "0..*" SendMailAdvCcInner : cc
SendMailAdv -- "0..*" SendMailAdvBccInner : bcc
SendMailAdv -- "0..*" SendMailAdvAttachmentsInner : attachments
MailLog -- "0..*" MailLogEntry : emails

@enduml