@startuml

title Mail Baby API Schemas Diagram

entity ErrorResponse { 
    * code: String
    * message: String
}

entity GenericResponse { 
    status: String
    status_text: String
}

entity MailAttachment { 
    * data: File
    filename: String
}

entity MailContact { 
    * email: String
    name: String
}

entity MailLog { 
    id: Long
}

entity MailOrder { 
    * id: Integer
    * status: String
    * username: String
    password: String
    comment: String
}

entity SendMail { 
    * subject: String
    * body: String
    * from: List<SendMailFrom>
    * to: List<MailContact>
    * id: Long
    replyto: List<MailContact>
    cc: List<MailContact>
    bcc: List<MailContact>
    attachments: List<MailAttachment>
}

entity SendMailFrom { 
    * email: String
    name: String
}


SendMail -- "0..*" SendMailFrom : from
SendMail -- "0..*" MailContact : to
SendMail -- "0..*" MailContact : replyto
SendMail -- "0..*" MailContact : cc
SendMail -- "0..*" MailContact : bcc
SendMail -- "0..*" MailAttachment : attachments

@enduml