//
// MailLog.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Paginated mail log response returned by &#x60;GET /mail/log&#x60;.  Contains the full matched count (&#x60;total&#x60;) plus a page of &#x60;MailLogEntry&#x60; records.  Use &#x60;skip&#x60; and &#x60;limit&#x60; to page through large result sets. */
public struct MailLog: Sendable, Codable, Hashable {

    /** Total number of log entries that match the supplied filters, regardless of `skip` and `limit`.  Use this to calculate the number of pages: `ceil(total / limit)`. */
    public var total: Int
    /** The `skip` value used for this page (echoed from the request). */
    public var skip: Int
    /** The `limit` value used for this page (echoed from the request). */
    public var limit: Int
    public var emails: [MailLogEntry]

    public init(total: Int, skip: Int, limit: Int, emails: [MailLogEntry]) {
        self.total = total
        self.skip = skip
        self.limit = limit
        self.emails = emails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case skip
        case limit
        case emails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(skip, forKey: .skip)
        try container.encode(limit, forKey: .limit)
        try container.encode(emails, forKey: .emails)
    }
}

