(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Mail_order_detail.t : Extended mail order record including the current SMTP password.  Returned by `GET /mail/{id}`.  The `username` and `password` fields can be used to authenticate directly against `relay.mailbaby.net:25` via SMTP AUTH if you prefer to send via a native SMTP client rather than the REST API.
 *)



    
        type t = {
                              id: int32
                  
                  
                
                
                ; [@key "id"]
                    (** The unique numeric ID of the mail order.  Used as the `id` parameter on sending calls, log queries, and stats queries. *)
                                      status: string
                  
                  
                
                
                ; [@key "status"]
                    (** The current order status.  Only `active` orders can be used for sending. `canceled` orders are retained for history but cannot send. *)
                                      username: string
                  
                  
                
                
                ; [@key "username"]
                    (** The SMTP AUTH username for this order, always in the format `mb<id>`. Use together with the password from `GET /mail/{id}` to authenticate directly against `relay.mailbaby.net:25` if needed. *)
                                      password: string
                  
                  
                
                
                ; [@key "password"]
                    (** The current SMTP AUTH password for this mail order.  Use with the `username` field to authenticate against `relay.mailbaby.net:25`. *)
                                      comment: string
                  
                   option [@default None]
                
                
                ; [@key "comment"]
                    (** Optional human-readable note associated with the order. *)
                } [@@deriving yojson { strict = false }, show, eq ];;
        
        (** Extended mail order record including the current SMTP password.  Returned by `GET /mail/{id}`.  The `username` and `password` fields can be used to authenticate directly against `relay.mailbaby.net:25` via SMTP AUTH if you prefer to send via a native SMTP client rather than the REST API. *)
        let create (id : int32) (status : string) (username : string) (password : string) : t = {
            id = id;
            status = status;
            username = username;
            password = password;
            comment = None;
        }
    

