(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 * Schema Send_mail_raw.t : Raw Email Object
 *)



    
        type t = {
                              raw_email: string
                  
                  
                
                
                ; [@key "raw_email"]
                    (** The entire email contents *)
                                      id: int32
                  
                   option [@default None]
                
                
                ; [@key "id"]
                    (** Optional order id *)
                } [@@deriving yojson { strict = false }, show, eq ];;
        
        (** Raw Email Object *)
        let create (raw_email : string) : t = {
            raw_email = raw_email;
            id = None;
        }
    

