/**
 * MailBaby Email Delivery and Management Service API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model


  /**
   * MailLogEntry
   * An email record
   */
case class MailLogEntry(
  /* internal db id */
  id: Int,
  /* mail id */
  id: String,
  /* from address */
  from: String,
  /* to address */
  to: String,
  /* email subject */
  subject: String,
  /* creation date */
  created: String,
  /* creation timestamp */
  time: Int,
  /* user account */
  user: String,
  /* transaction type */
  transtype: String,
  /* origin ip */
  origin: String,
  /* interface name */
  interface: String,
  /* sending zone */
  sendingZone: String,
  /* email body size in bytes */
  bodySize: Int,
  /* index of email in the to adderess list */
  seq: Int,
  /* to address this email is being sent to */
  recipient: String,
  /* to address domain */
  domain: String,
  /* locked status */
  locked: Int,
  /* lock timestamp */
  lockTime: String,
  /* assigned server */
  assigned: String,
  /* queued timestamp */
  queued: String,
  /* mx hostname */
  mxHostname: String,
  /* mail delivery response */
  response: String,
  /* message id */
  messageId: Option[String] = None
)

