-module(openapi_mail_log_entry).

-export([encode/1]).

-export_type([openapi_mail_log_entry/0]).

-type openapi_mail_log_entry() ::
    #{ '_id' := integer(),
       'id' := binary(),
       'from' := binary(),
       'to' := binary(),
       'subject' := binary(),
       'messageId' := binary(),
       'created' := binary(),
       'time' := integer(),
       'user' := binary(),
       'transtype' := binary(),
       'transhost' := binary(),
       'originhost' := binary(),
       'origin' := binary(),
       'interface' := binary(),
       'date' := binary(),
       'sendingZone' := binary(),
       'bodySize' := integer(),
       'sourceMd5' := binary(),
       'seq' := integer(),
       'domain' := binary(),
       'recipient' := binary(),
       'locked' := integer(),
       'lockTime' := integer(),
       'assigned' := binary(),
       'queued' := binary(),
       '_lock' := binary(),
       'logger' := binary(),
       'mxPort' := integer(),
       'connectionKey' := binary(),
       'mxHostname' := binary(),
       'sentBodyHash' := binary(),
       'sentBodySize' := integer(),
       'md5Match' := integer()
     }.

encode(#{ '_id' := Id,
          'id' := Id,
          'from' := From,
          'to' := To,
          'subject' := Subject,
          'messageId' := MessageId,
          'created' := Created,
          'time' := Time,
          'user' := User,
          'transtype' := Transtype,
          'transhost' := Transhost,
          'originhost' := Originhost,
          'origin' := Origin,
          'interface' := Interface,
          'date' := Date,
          'sendingZone' := SendingZone,
          'bodySize' := BodySize,
          'sourceMd5' := SourceMd5,
          'seq' := Seq,
          'domain' := Domain,
          'recipient' := Recipient,
          'locked' := Locked,
          'lockTime' := LockTime,
          'assigned' := Assigned,
          'queued' := Queued,
          '_lock' := Lock,
          'logger' := Logger,
          'mxPort' := MxPort,
          'connectionKey' := ConnectionKey,
          'mxHostname' := MxHostname,
          'sentBodyHash' := SentBodyHash,
          'sentBodySize' := SentBodySize,
          'md5Match' := Md5Match
        }) ->
    #{ '_id' => Id,
       'id' => Id,
       'from' => From,
       'to' => To,
       'subject' => Subject,
       'messageId' => MessageId,
       'created' => Created,
       'time' => Time,
       'user' => User,
       'transtype' => Transtype,
       'transhost' => Transhost,
       'originhost' => Originhost,
       'origin' => Origin,
       'interface' => Interface,
       'date' => Date,
       'sendingZone' => SendingZone,
       'bodySize' => BodySize,
       'sourceMd5' => SourceMd5,
       'seq' => Seq,
       'domain' => Domain,
       'recipient' => Recipient,
       'locked' => Locked,
       'lockTime' => LockTime,
       'assigned' => Assigned,
       'queued' => Queued,
       '_lock' => Lock,
       'logger' => Logger,
       'mxPort' => MxPort,
       'connectionKey' => ConnectionKey,
       'mxHostname' => MxHostname,
       'sentBodyHash' => SentBodyHash,
       'sentBodySize' => SentBodySize,
       'md5Match' => Md5Match
     }.
