/**
 * MailBaby Email Delivery and Management Service API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * OpenAPI spec version: 1.3.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#pragma once

#include "OpenAPIBaseModel.h"

namespace OpenAPI
{

/*
 * OpenAPIMailLogEntry
 *
 * An email record
 */
class OPENAPI_API OpenAPIMailLogEntry : public Model
{
public:
    virtual ~OpenAPIMailLogEntry() {}
	bool FromJson(const TSharedPtr<FJsonValue>& JsonValue) final;
	void WriteJson(JsonWriter& Writer) const final;

	/* internal db id */
	int32 Id = 0;
	/* mail id */
	FString Id;
	/* from address */
	FString From;
	/* to address */
	FString To;
	/* email subject */
	FString Subject;
	/* creation date */
	FString Created;
	/* creation timestamp */
	int32 Time = 0;
	/* user account */
	FString User;
	/* transaction type */
	FString Transtype;
	/* origin ip */
	FString Origin;
	/* interface name */
	FString Interface;
	/* sending zone */
	FString SendingZone;
	/* email body size in bytes */
	int32 BodySize = 0;
	/* index of email in the to adderess list */
	int32 Seq = 0;
	/* to address this email is being sent to */
	FString Recipient;
	/* to address domain */
	FString Domain;
	/* locked status */
	int32 Locked = 0;
	/* lock timestamp */
	FString LockTime;
	/* assigned server */
	FString Assigned;
	/* queued timestamp */
	FString Queued;
	/* mx hostname */
	FString MxHostname;
	/* mail delivery response */
	FString Response;
	/* message id */
	TOptional<FString> MessageId;
};

}
