# coding: utf-8

"""
    MailBaby Email Delivery API

    **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**   # 📌 Overview  This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).   # 🔐 Authentication  In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.  We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@interserver.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_mail_orders(self):
        """Test case for get_mail_orders

        displays a list of mail service orders  # noqa: E501
        """
        pass

    def test_ping_server(self):
        """Test case for ping_server

        Checks if the server is running  # noqa: E501
        """
        pass

    def test_send_adv_mail(self):
        """Test case for send_adv_mail

        Sends an Email with Advanced Options  # noqa: E501
        """
        pass

    def test_send_mail(self):
        """Test case for send_mail

        Sends an Email  # noqa: E501
        """
        pass

    def test_view_mail_log(self):
        """Test case for view_mail_log

        displays the mail log  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
