/* 
 * MailBaby Email Delivery and Management Service API
 *
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.** # Overview This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net). # Authentication In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site. We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@interserver.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MailStatsTypeVolumeTo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MailStatsTypeVolumeToTests
    {
        // TODO uncomment below to declare an instance variable for MailStatsTypeVolumeTo
        //private MailStatsTypeVolumeTo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MailStatsTypeVolumeTo
            //instance = new MailStatsTypeVolumeTo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MailStatsTypeVolumeTo
        /// </summary>
        [Test]
        public void MailStatsTypeVolumeToInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MailStatsTypeVolumeTo
            //Assert.IsInstanceOfType<MailStatsTypeVolumeTo> (instance, "variable 'instance' is a MailStatsTypeVolumeTo");
        }


        /// <summary>
        /// Test the property 'ClientdomainCom'
        /// </summary>
        [Test]
        public void ClientdomainComTest()
        {
            // TODO unit test for the property 'ClientdomainCom'
        }
        /// <summary>
        /// Test the property 'UsersiteNet'
        /// </summary>
        [Test]
        public void UsersiteNetTest()
        {
            // TODO unit test for the property 'UsersiteNet'
        }
        /// <summary>
        /// Test the property 'SalescompanyCom'
        /// </summary>
        [Test]
        public void SalescompanyComTest()
        {
            // TODO unit test for the property 'SalescompanyCom'
        }
        /// <summary>
        /// Test the property 'ClientanothersiteCom'
        /// </summary>
        [Test]
        public void ClientanothersiteComTest()
        {
            // TODO unit test for the property 'ClientanothersiteCom'
        }

    }

}
