/**
 * MailBaby Email Delivery and Management Service API
 *
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EmailAddressName } from './emailAddressName';


/**
 * 
 */
/**
 * @type EmailAddressTypes
 * 
 * @export
 */
export type EmailAddressTypes = EmailAddressName | string;

