export * from './Body';
export * from './ErrorResponse';
export * from './GenericResponse';
export * from './MailAttachment';
export * from './MailContact';
export * from './MailLog';
export * from './MailOrder';
export * from './SendMailAdv';
export * from './SendMailAdvFrom';
