/**
 * MailBaby Email Delivery API
 * **Send emails fast and with confidence through our easy to use [REST](https://en.wikipedia.org/wiki/Representational_state_transfer) API interface.**   # 📌 Overview  This is the API interface to the [Mail Baby](https//mail.baby/) Mail services provided by [InterServer](https://www.interserver.net). To use this service you must have an account with us at [my.interserver.net](https://my.interserver.net).   # 🔐 Authentication  In order to use most of the API calls you must pass credentials from the [my.interserver.net](https://my.interserver.net/) site.  We support several different authentication methods but the preferred method is to use the **API Key** which you can get from the [Account Security](https://my.interserver.net/account_security) page. 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: support@interserver.net
 *
 * NOTE: This class is auto generated by OpenAPI Generator
 * https://github.com/OpenAPITools/openapi-generator
 * Do not edit the class manually.
 */

#include "OpenAPISendMailAdv.h"

#include "OpenAPIModule.h"
#include "OpenAPIHelpers.h"

#include "Templates/SharedPointer.h"

namespace OpenAPI
{

void OpenAPISendMailAdv::WriteJson(JsonWriter& Writer) const
{
	Writer->WriteObjectStart();
	Writer->WriteIdentifierPrefix(TEXT("subject")); WriteJsonValue(Writer, Subject);
	Writer->WriteIdentifierPrefix(TEXT("body")); WriteJsonValue(Writer, Body);
	Writer->WriteIdentifierPrefix(TEXT("from")); WriteJsonValue(Writer, From);
	Writer->WriteIdentifierPrefix(TEXT("to")); WriteJsonValue(Writer, To);
	if (Replyto.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("replyto")); WriteJsonValue(Writer, Replyto.GetValue());
	}
	if (Cc.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("cc")); WriteJsonValue(Writer, Cc.GetValue());
	}
	if (Bcc.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("bcc")); WriteJsonValue(Writer, Bcc.GetValue());
	}
	if (Attachments.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("attachments")); WriteJsonValue(Writer, Attachments.GetValue());
	}
	if (Id.IsSet())
	{
		Writer->WriteIdentifierPrefix(TEXT("id")); WriteJsonValue(Writer, Id.GetValue());
	}
	Writer->WriteObjectEnd();
}

bool OpenAPISendMailAdv::FromJson(const TSharedPtr<FJsonValue>& JsonValue)
{
	const TSharedPtr<FJsonObject>* Object;
	if (!JsonValue->TryGetObject(Object))
		return false;

	bool ParseSuccess = true;

	ParseSuccess &= TryGetJsonValue(*Object, TEXT("subject"), Subject);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("body"), Body);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("from"), From);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("to"), To);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("replyto"), Replyto);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("cc"), Cc);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("bcc"), Bcc);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("attachments"), Attachments);
	ParseSuccess &= TryGetJsonValue(*Object, TEXT("id"), Id);

	return ParseSuccess;
}

}
